sudo: false
language: python
python:
 - "3.9.4"

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.pip-accel

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

install:
  - pip install pip-accel
  - pip-accel install -q coveralls
  - pip-accel install -q -r requirements/development.txt

script:
  - flake8
  - coverage run --source='fossevents' --omit='*tests*,*requirements*,*commands*,*migrations*,*admin*,*wsgi*' -m py.test -v --tb=native

# report coverage to coveralls.io
after_success: coveralls

deploy:
  provider: heroku
  buildpack: python
  strategy: git
  api_key:
    secure: ifPDQ9zzJ9rrpiIubGlv53GCC4o+75j3WJX8A4vtdNcUtkuG26/xmoMKKC2yXa9EnRCzXe2oFAtNxXso1OqjWarfErzNQLHFVpy2mA0wpYTjPx026VPcFI/qH0PgMQzQySvaRfrrM2yLshrA4QFEoxhIxGZaNMwQe2rrFN8GZDQ=
  app:
    master: fossevents
  on:
    repo: fossevents/fossevents.in
